---
title: ""
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Research questions and hypotheses

**RQ1:** To what extent do math attitudes (math anxiety, math avoidance, math self-competence, academic buoyancy, worry) predict students’ behaviours (skipping, help-seeking, self-reliance) during the mathematical task?

**HP1:** controlling for math ability (T0) and metacognition, higher trait math anxiety and math avoidance are expected to increase the likelihood of skipping behaviours. Lower avoidance and higher academic buoyancy are expected to increase the likelihood of self-reliance behaviours. Lower avoidance, together with moderate levels of anxiety and buoyancy, are expected to increase the likelihood of help-seeking behaviours.

This hypotesis will be tested using a multinomial logistic regression that will thus feature the following formula:
$$
\begin{equation}
\text{logit}\big(P(Y_{ij} = k)\big) = 
\beta_{0k} 
+ \beta_{1k} \cdot \text{Anxiety}_{ij} 
+ \beta_{2k} \cdot \text{Avoidance}_{ij} 
+ \beta_{3k} \cdot \text{SelfComp}_{ij} 
+ \beta_{4k} \cdot \text{Buoyancy}_{ij}
+ \beta_{5k} \cdot \text{Worry}_{ij}
+ \beta_{6k} \cdot \text{Metacognition}_{ij} 
+ \beta_{7k} \cdot \text{MathAbility}_{ij} 
+ u_{0j}^{(k)}
\end{equation}
$$

Where:

- $Y_{ij}$ is the observed outcome of child $j$ in for observation $i$,
- $k$ is the category of the dependent variable,
- $\beta_{0k}$ is the intercept for the category $k$,
- $\beta_{1k}, \dots, \beta_{7k}$ are the fixed coefficients for the predictorts (math ability and metacognition are covariate),
- $u_{0j}^{(k)}$ is the random effect ID (student $j$ for the category $k$, the behaviour chosen).<br><br>
<br><br>

**RQ2:** Do skipping problems, help-seeking and self-reliance behaviours predict students’ mathematical performance?

**HP2:** Controlling for math ability (T0), self-reliance and help-seeking behaviours are expected to predict a higher probability of mathematical performance (T1) compared to skipping behaviours.


This hypotesis will be tested using a logistic regression that will thus feature the following formula:
$$
\begin{equation}
\text{logit}\big(P(Y_{ij} = k)\big) = 
\beta_{0} 
+ \beta_{1} \cdot \text{SelfReliance}_{ij} 
+ \beta_{2} \cdot \text{HelpSeeking}_{ij} 
+ \beta_{3} \cdot \text{Skipping}_{ij} 
+ \beta_{4} \cdot \text{MathAbility}_{ij}
+ u_{0j}
\end{equation}
$$


Where:

- $Y_{ij}$ is the observed outcome of child $j$ in for observation $i$,
- $\beta_{0k}$ is the intercept,
- $\beta_{1k}, \dots, \beta_{4k}$ are the fixed coefficients for the predictors (math ability as covariate),
- $u_{j}$ is the random effect of the participant. 




